# Generated by Django 5.0.6 on 2024-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
            ],
        ),
    ]
